chart/templates/drupal-volumes.yaml, chart/values.yaml
Adding two straightforward fixes from the charts repository:
- https://github.com/wunderio/charts/pull/4
- https://github.com/wunderio/charts/pull/10
=> Storage fixes

chart/requirements.lock, chart/requirements.yaml, chart/templates/_helpers.tpl, chart/tests/mariadb_test.yaml, chart/tests/memcached_test.yaml, chart/values.yaml, web/sites/default/settings.php
Story: https://wunder.atlassian.net/browse/SLT-92
Memcache resource, available at `MEMCACHED_HOST`, also setting `$settings['memcache']['servers']` when available.
=> SLT-92: Memcached support

chart/templates/_helpers.tpl, web/sites/default/settings.php, web/sites/default/settings.silta.php
- `SILTA_CLUSTER` environment variable created
- `sites/default/settings.silta.php` included when the `SILTA_CLUSTER` variable is set
- some settings moved to `settings.silta.php`
=> SLT-164: Separate settings.silta.php that is used in cluster environment

.circleci/config.yml
We want to keep the orb definition inline in this repository to facilitate the development process, the published orb definition will live at https://github.com/wunderio/silta-circleci.
The `workflows` section of the CircleCI configuration file will be the only part that is included in the project repositories.
There is a need for some discussion, especially about the possibilities to include custom steps in certain places (additional validation, build steps, etc). We should also have related pull requests for the silta-circleci and drupal-project repositories.
=> Inline CircleCI orb definition

chart/templates/_helpers.tpl, chart/templates/drupal-volumes.yaml, chart/templates/shell-deployment.yaml, chart/tests/private_files_test.yaml, chart/tests/reference_data_test.yaml, chart/values.yaml
Moves ssh fingerprint keys into separate mounted folder
=> SLT-187: Mount ssh keys onto persistent storage that lives trough deployments

web/sites/default/settings.lando.php, web/sites/default/settings.php
Related issue: https://github.com/wunderio/silta/issues/1#issuecomment-472060811
Followup PR's: 
- https://github.com/wunderio/drupal-project/pull/22
- https://github.com/wunderio/silta/pull/3
=> Dedicated lando settings file

.circleci/config.yml
A set of simple checks regarding issues we have seen in the past (generally about certain key files missing from the repository).
=> SLT-234 basic checks

.circleci/config.yml
See https://github.com/wunderio/silta-circleci/pull/17
=> SLT-253: Make the deployment optional.

chart/tests/private_files_test.yaml, chart/tests/reference_data_test.yaml, chart/tests/volumes_test.yaml
Minor adjustments to the tests so the assertions match to the right document in a multi-document yaml file. These probably need to be revised in the future, this is just the minimum change to make things pass without changing the logic.
=> SLT-257: Update tests to match the new volume structures.

composer.json, composer.lock
See https://www.jeffgeerling.com/blog/2018/make-composer-operations-drupal-way-faster-and-easier-on-ram 
for how this package makes composer faster and solves common memory issues.
=> Add zaporylie/composer-drupal-optimizations

chart/templates/_helpers.tpl
We only needed this check for nfs which took some time to be available. 
Tested the change in a dedicated testing branch https://circleci.com/gh/wunderio/drupal-project-k8s/6177
=> SLT-269: remove waiting on filesystem

chart/templates/varnish-configmap-vcl.yaml, chart/templates/varnish-deployment.yaml
- Add a liveness check
- Update 500 error page according to feedback from our design circle. See the result here. http://feature-enable-varnish.drupal-project-k8s.silta.wdr.io/ (I manually edited the readiness check of the drupal deployment to always fail).
=> Varnish improvements

chart/templates/NOTES.txt, chart/templates/drupal-service.yaml, chart/values.yaml
Refactor exposeDomains to allow adding certificates for each domain in the future
=> exposeDomains refactor

chart/templates/_helpers.tpl, chart/tests/drupal_deployment_test.yaml
```
$ env
ENVIRONMENT_NAME=feature/SLT-345-environmentName
```
=> SLT-345: environmentName in php env variables

charts/drupal/templates/drupal-configmap.yaml, charts/drupal/tests/drupal_configmap_test.yaml, charts/drupal/values.yaml
Allows having custom PHP ini directives.
=> Custom PHP settings block.

charts/drupal/templates/drupal-ingress.yaml, charts/drupal/templates/drupal-service.yaml, charts/drupal/values.yaml, charts/silta-release/values.schema.json, silta/silta.yml
This PR adds the annotation to automatically downscaling with https://github.com/wunderio/charts/pull/101
=> Support for auto-downscaling

charts/drupal/README.md
Lists chart provided environment variables available in container. 
Rendered example here: https://github.com/wunderio/drupal-project-k8s/tree/feature/slt-417-env-list/charts/drupal#available-environment-variables
=> Environment variable listing

charts/drupal/templates/drupal-configmap.yaml, charts/drupal/values.yaml
Allows having custom configuration in location context.
=> Custom nginx configuration block in location context via locationExtraConfig

charts/drupal/templates/varnish-configmap-vcl.yaml, charts/drupal/values.yaml
Jira issue: https://wunder.atlassian.net/browse/SLT-564
Replicates https://github.com/wunderio/WunderMachina/blob/master/playbook/roles/varnish/templates/default.vcl.j2#L257:L261
=> Add vcl_extra_cookies variable for extra varnish cookie rules.

charts/drupal/templates/drupal-configmap.yaml, silta/silta.yml
php-fpm access log to stdout is impossible currently
=> php-fpm logging improvements

charts/drupal/Chart.lock, charts/drupal/files/settings.silta.d7.php, charts/drupal/files/settings.silta.php, charts/drupal/templates/_helpers.tpl, charts/drupal/templates/drupal-configmap.yaml, charts/drupal/values.yaml, silta/silta.yml
Updated the memcache setting changes from the charts repository.
=> SLT-505: Port the memcache settings changes from charts repository

charts/drupal/templates/varnish-configmap-vcl.yaml, charts/drupal/values.yaml, silta/silta.yml
Allows overriding varnish http status 500 page html
=> Varnish status 500 html

.lando.yml, .lando/php.ini, .lando/xdebug.sh, composer.json, composer.lock, grumphp.yml, lando-docker-compose.yml
**Code quality tool update**
**Features:**
- Updates code quality tool and underlying grumphp packages.
- Updates .lando.yml to support latest version of lando and required php version.
- Fixes grumphp configurations.
=> Upgrade code quality and lando

charts/drupal/Chart.yaml, charts/drupal/templates/varnish-deployment.yaml, silta/silta.yml
Returns missing varnish volumes
=> varnish volume fix

charts/drupal/templates/drupal-backendconfig.yaml, silta/silta.yml
Dont create BackendConfig resource on empty variable.
=> Optional backendconfig

charts/drupal/templates/drupal-configmap.yaml, charts/drupal/values.yaml
Disabling gdprdump due to unavailable gdpr-dump extended mysqldump binary
=> Disabling gdprdump

charts/drupal/templates/_helpers.tpl, silta/silta.yml
Lower compression level in backup pods.
=> Backup compression

charts/drupal/templates/solr-statefulset.yaml
This should resolve SOLR 5.x compatibilty issues
=> SOLR 5.x compatibility

.circleci/config.yml, charts/drupal/templates/drupal-ingress.yaml, silta/silta-aks.yml
- Ingress resource fix for v1+
- AKS deployments
=> AKS deployment test with custom orb and cicd image

charts/drupal/templates/backup-volume.yaml, charts/drupal/templates/drupal-volumes.yaml, charts/drupal/templates/shell-volume.yaml
Adds annotation for subpath on backup, shell keys volumes.
=> fs annotations

charts/drupal/values.yaml
- move one comment a few lines further down, since the comment specifically regards the drupal cron job
- add note about resource inheritance
=> Improved documentation about php cron jobs.

charts/drupal/templates/_helpers.tpl, charts/drupal/tests/drupal_ingress_test.yaml
gke kubernetes version seems to mess up semversion comparison
=> Conditional api attempt #3

.circleci/config.yml, silta/silta-master-aks.yml
- Initiates master branch build to AKS cluster after code merge to master branch
- Tests master deployment sites on GCP and AKS
- Weekly automated builds and site testing (Friday 8AM, no idea what's the timezone of scheduled executor)
=> Run test deployment to aks cluster

charts/drupal/templates/_helpers.tpl, charts/drupal/templates/drupal-ingress.yaml, charts/drupal/templates/drupal-service.yaml, charts/drupal/templates/varnish-service.yaml
- Downscaler annotation fix, 
- also removes puzzling `Creating drupal database.` message from post-upgrade job
=> Downscaler annotation fix

charts/drupal/Chart.yaml, charts/drupal/values.yaml
Use updated mariadb subchart fork, disable enableServiceLinks by default
=> Trigger subchart update; disable enableServiceLinks by default

charts/drupal/templates/drupal-deployment.yaml, charts/drupal/tests/drupal_hpa_test.yaml, charts/drupal/values.yaml
Abstracts HPA rules on top of pre 1.23 style rules to enable compatibility with autoscaling api configuration schema changes
=> hpa 1.23+ definition change

charts/drupal/values.yaml
Not sure if the units should be changed somewhere else too.
=> Change units from bytes to bibytes

charts/drupal/templates/_helpers.tpl
A follow up to #554 
- remove duplicate echo line
- add echos when saving db dumps
- echo which db dump file is being imported
=> Ref data: Follow up to #554

charts/drupal/templates/drupal-deployment.yaml
=> Fixing mixed up values

charts/drupal/templates/drupal-configmap.yaml, charts/drupal/templates/drupal-deployment.yaml, charts/drupal/templates/drupal-secret.yaml, charts/drupal/values.schema.json, charts/drupal/values.yaml
=> Release 2023-06-08

charts/drupal/templates/drupal-ingress.yaml, charts/drupal/values.yaml
"Expose" releaseMinAge to developers to allow them to control when the deployment will be Downscaled
-- Still needs change in the[ downscaler repo](https://github.com/wunderio/silta-downscaler) to use the value 
Test with downscaler
=> SLT-775: Allow releaseMinAge to be annotated to ingress

charts/drupal/templates/drupal-ingress.yaml, charts/drupal/tests/drupal_ingress_test.yaml
Late implementation of  `ingressClassName` spec support
GCE note: https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#controller_summary
=> Conditional ingressClassName spec

charts/drupal/values.schema.json
=> chart values schema

.circleci/config.yml, charts/drupal/Chart.lock, charts/drupal/Chart.yaml, charts/drupal/values.yaml, charts/silta-release/Chart.yaml, silta/nginx.Dockerfile
image version adjustments for Silta 1.0 initiative
Note: don't forget to sync `silta-release` library chart to charts repository!
=> silta v1 tags

charts/drupal/files/settings.silta.d7.php, charts/drupal/files/settings.silta.php
Port can be changed by using DB_PORT environment variable. Otherwise, it defaults to 3306.
=> allow for custom db ports

charts/drupal/Chart.yaml, charts/drupal/templates/_helpers.tpl
Use DB_PORT env var, if its available. Otherwise, default to 3306.
=> post release port

silta/silta.yml
This is an addition to #675 based on Tormis suggestion at https://github.com/wunderio/drupal-project/pull/379#pullrequestreview-1797492947
=> SLT-898: Use non-existing date for feature environment cron job

charts/drupal/templates/drupal-cron.yaml, charts/drupal/values.schema.json
Allows unsetting default cronjobs or cronjobs from shared cronjob list for release-suffixed deployments
=> Allow unsetting cronjobs

.circleci/config.yml
A spin off from #691 with approvals before build step
=> SLT-962: Manual approval for feature deployments

charts/drupal/templates/drupal-configmap.yaml
- adds robots header to sections that have existing add_header directive
- adds header for non-200 pages
=> Adds robots header for location scope; adds header for non-200 pages

.circleci/config.yml, silta/php.Dockerfile, silta/shell.Dockerfile
Link to ticket: https://wunder.atlassian.net/browse/SLT-1052
=> Use php 8.3 images

.circleci/config.yml, charts/drupal/templates/_helpers.tpl, charts/drupal/templates/image-secrets.yaml, charts/drupal/values.schema.json, charts/drupal/values.yaml
Allows setting custom imagePullSecret
=> Add support for custom imagePullSecret

charts/silta-release/templates/_networkPolicy.tpl, charts/silta-release/tests/network_policy_test.yaml, charts/silta-release/values.yaml
Use immutable namespace selector, available since 1.22
=> Immutable namespace selector

charts/drupal/templates/_helpers.tpl
https://dev.mysql.com/doc/refman/8.4/en/mysqladmin.html#option_mysqladmin_connect-timeout
Reported by @ArtisKrumins
=> connect-timeout typo fix

charts/drupal/templates/serviceaccount.yaml
=> Fix for SA automount

charts/drupal/templates/_helpers.tpl
Backup process improvement. 30s delay to allow mariadb contains to finish starting up. added max_allowed_packet argument to avoid dump and import validation failing when database cell is too big for reason
=> Backup improvements

charts/drupal/templates/drupal-configmap.yaml, charts/drupal/tests/drupal_configmap_test.yaml, charts/drupal/values.schema.json, charts/drupal/values.yaml
Blocks https://github.com/wunderio/silta-circleci/pull/216
=> SLT-1191: Make signalsciences work with old and new nginx versions

charts/drupal/Chart.lock, charts/drupal/Chart.yaml, charts/drupal/values.yaml
Use forked binami chart version with image location overrides
=> Use forked charts
