- chart/templates/_helpers.tpl
- chart/templates/drupal-cron.yaml
- chart/templates/drupal-deployment.yaml
- chart/templates/postinstall.yaml
- chart/tests/drupal_cron_test.yaml
- chart/tests/drupal_deployment_test.yaml
- chart/tests/drupal_postinstall_test.yaml
- chart/tests/private_files_test.yaml
Adding some additional tests pointed out that some things were missing in a few places: cron was missing volumes, postinstall was missing private files. Fixing these issues was done by defining the php container as a template, similar to what was done in https://github.com/wunderio/charts/pull/8/files.
> SLT-121 more tests

- chart/templates/_helpers.tpl
- chart/templates/drupal-cron.yaml
- chart/templates/drupal-deployment.yaml
- chart/templates/postinstall.yaml
- chart/tests/private_docker_image_test.yaml
- chart/values.yaml
Based on https://github.com/wunderio/charts/pull/7
We do not actually need to have pull secrets configured on GKE. When we do, these should be based on a single configuration entry.
> SLT-147: make pull secrets for docker images configurable

- chart/templates/drupal-cron.yaml
- chart/tests/drupal_cron_test.yaml
- chart/values.yaml
Based on the work done by Agnis in https://github.com/wunderio/drupal-project-k8s/tree/feature/SLT-99-cron and by Jonathan in https://github.com/wunderio/charts/pull/3/files
We want to enable multiple cron jobs, for example, one for `drush cron`, and one for a dedicated queue. The use of the root scope `$` greatly simplifies the use of global variables in a loop.
> SLT-99 configurable cron

- chart/templates/postinstall.yaml
See https://github.com/helm/helm/blob/master/docs/charts_hooks.md#automatically-delete-hook-from-previous-release
Using "before-hook-creation" makes it possible to reinstall a release that failed in postinstall; without this Helm will try to  reinstall but fail because the failed postinstall job is still hanging around.
I'm not actually sure you want to delete the postinstall job if it's successful, it might have useful troubleshooting info even if it succeeded. But you definitely do want it deleted when you try to reinstall ...
> Use "before-hook-creation" for postinstall cleanup

- chart/templates/postupgrade.yaml
This one got added in a parallel branch, it missed the cleanup of the gcr imagePullSecrets.
> Stray reference to gcr in postupgrade

- chart/templates/_helpers.tpl
- chart/templates/drupal-configmap-nginx.yaml
- chart/templates/drupal-configmap-php.yaml
- chart/templates/drupal-deployment.yaml
- chart/values.yaml
Stories: 
Move nginx env vars from pod definition to base docker image (SLT-148)
Configure php.ini using a ConfigMap mounted as a volume (SLT-144)
Implementation:
Added 2 configmap templates: 
drupal-configmap-nginx.yaml (defines /etc/nginx/nginx.conf and /etc/nginx/conf.d/drupal.conf
(env vars in docker image were not used, added nginx config as configmap with option to define loglevel from values.yml)
drupal-configmap-php.yaml (defines  /etc/php7/php.ini, /etc/php7/php-fpm.conf, /etc/php7/php-fpm.d/www.conf)
In values.yml defined few options that get included in these configs
Values.nginx.loglevel
Values.drupal.php.post_max_size
Values.drupal.php.upload_max_filesize
Added respective volumes and mounts in _helpers.tpl and drupal-deployment.yaml
> Feature/configmaps (SLT-148; SLT-144)

- web/sites/default/settings.php
To test, just run:
```
lando start
lando drush site-install
```
This should run without errors.
> Load database credentials from Lando.

- chart/templates/_helpers.tpl
- chart/templates/drupal-deployment.yaml
- chart/templates/drupal-service.yaml
- chart/templates/drupal-volumes.yaml
- chart/values.yaml
Gitlab offers terminal access to K8s environments from the Gitlab UI, and UI feedback on deployments but only if  "app" has a specific value `app=$CI_ENVIRONMENT_SLUG`.
So how about allowing parent charts to customise the app name if they want to?
> Define app name as a helper

- chart/templates/drupal-deployment.yaml
Based on our discussion from earlier today, we shouldn't restart the php-fpm container if it can't connect to the database, as that's probably won't fix the source of the problem.
> Replace the drush liveness probe with a simple check of the tcp socket.

- web/sites/default/settings.php
By default, Twig templates are compiled as PHP files which are stored along with uploaded assets. This is not only a potential minor security issue, but it can also have a performance impact as shared storage is usually slower. 
To check:
- sites/default/files should not contain a "php" folder
- /tmp should contain a "twig" folder where the compiled php files are located
> Generated twig files should not be on shared storage.

- chart/README.md
Rather than documenting all the options in a markdown table, I think it's easier to point people directly to the values.yaml file where there are now some comments for all the options.
> SLT-146: Add a README file to the chart explaining how it is used.

- .circleci/config.yml
- Dockerfile
- README.md
- chart/templates/_helpers.tpl
- chart/templates/drupal-volumes.yaml
- chart/templates/postinstall.yaml
- chart/templates/postupgrade.yaml
- chart/templates/reference-data-cron.yaml
- chart/tests/reference_data_test.yaml
- chart/values.yaml
- gdpr.json
**What this PR does:**
I've set up a cron rule that is invoked every day at 3:00 AM and runs a `drush sql-dump` command provided by [GDPR Tools](https://github.com/machbarmacher/gdpr-dump). The sql dump is only run when the current branchname equals predefined `production_branchname` in `values.yaml`
We have a [slightly modified](https://github.com/Jancis/gdpr-dump) version currently because of following issues/improvements:
- ~https://github.com/machbarmacher/gdpr-dump/pull/28~
- https://github.com/machbarmacher/gdpr-dump/issues/26 
Once the issues are fixed, we can go back to [original](https://github.com/machbarmacher/gdpr-dump). 
This allows site developers to create a `/gdpr.json` file with [Faker](https://packagist.org/packages/fzaninotto/faker) formatters that will allow replacing …
> SLT-17: Periodical drush SQL-Dump using gdpr-dump.

- chart/templates/drupal-deployment.yaml
Liveness checks: If nginx is not listening on port 80, we need to kill the container. We don't want to do an HTTP request on port 80, because most requests are forwarded to the php container, and if that one fails we would be killing the wrong container.
Readiness checks: For this one we actually want to wait until we are serving successful responses before we start serving traffic from that container.
> SLT-161: Add readiness and liveness checks to nginx.

- .circleci/config.yml
- chart/templates/postinstall.yaml
- chart/templates/postupgrade.yaml
- chart/values.yaml
You can delete the `w68f3d122-b5a8b6f7-feature-reference-da` release and re-run the last deployment from https://circleci.com/gh/wunderio/drupal-project-k8s/tree/feature%2Freference-data-import, you will then get a working environment running on http://feature-reference-data-import.drupal-project-k8s.silta.wdr.io/ based on the latest reference database dump. Note that name of the admin user is set to a random generated value, thanks to the GDPR sanitization.
What is not included and moved to a dedicated ticket:
- Optimise the dumps so the cache tables are not included
- Copy the drupal ~public and~ private files 
- Skip dumps if the gdpr-dump package is not present
> SLT-166: Import reference database dump for new environments

- chart/templates/_helpers.tpl
- chart/templates/drupal-deployment.yaml
We are facing this issue: https://github.com/helm/helm/issues/2494
The pod selector for a deployment and the label template need to be identical, the selector is also immutable. This leads to a problem when the chart version is used as a label, upgrading to a newer version is then not allowed.
This fix itself breaks an upgrade because it changes an immutable field. There is no need to delete the whole release though, it is sufficient to delete the deployment and re-run the helm upgrade.
> SLT-162 deployment selector fix

- .circleci/config.yml
- chart/values.yaml
- composer.json
- composer.lock
- drush/drush.yml
The main changes are:
- Use the official version of machbarmacher/gdpr-dump now that https://github.com/machbarmacher/gdpr-dump/pull/28 and https://github.com/machbarmacher/gdpr-dump/pull/27 have been merged
- Only create a reference dump if machbarmacher/gdpr-dump is installed and configured. 
This code only runs automatically on the reference branch, I ran it manually on the environment for testing purposes.
> SLT-173 & SLT-170: streamline gdpr-dump usage

- .circleci/config.yml
- chart/templates/reference-data-cron.yaml
- chart/values.yaml
**Story:**
https://wunder.atlassian.net/browse/SLT-169
**What this PR does:**
- Fixes related thing (by adjusting the addition syntax to work on `sh`):
```
Waiting for database...
/bin/sh: TIME_WAITING: not found
Waiting for database...
/bin/sh: TIME_WAITING: not found
```
- Lists failed releases, looks for a release with exact name, and extracts second column (release number). Compares with "1" and removes the release if it matches.
Other ways to solve this:
- use `helm upgrade --force`, but it could potentially remove some production site data in case it's marked as failed, so we really need this for the first deployment
-  smarter way to extract release number, like matching on `helm get`, but the string matching there could potentially get false positive on releases "10-19; 100-199; …
> SLT-169: Removes failed release before deployment if it was the first release

- chart/templates/_helpers.tpl
Generates correct hostname for `drush uli` command when it's run inside the `shell` container
> SLT-188: Inject DRUSH_OPTIONS_URI environment variable

- chart/templates/post-release.yaml
Most of the time, if a post-release hook fails it's because of an issue with the project (invalid configuration, etc), so retrying up to 6 times with increasing intervals (the default behavior for kubernetes jobs) is not helpful. It actually easily leads to a timeout, at which point the call to `helm upgrade` fails and the logs are not displayed.
> SLT-193: Only try to run post-release hooks a single time.

- chart/templates/_helpers.tpl
- chart/templates/drupal-configmap-nginx.yaml
- chart/templates/drupal-configmap-php.yaml
- chart/templates/drupal-cron.yaml
- chart/templates/drupal-deployment.yaml
- chart/templates/drupal-secret.yaml
- chart/templates/drupal-service.yaml
- chart/templates/drupal-volumes.yaml
- chart/templates/elasticsearch.yaml
- chart/templates/post-release.yaml
- chart/templates/reference-data-cron.yaml
- chart/templates/shell-deployment.yaml
- chart/templates/shell-service.yaml
The main issue with the output of our helm chart was the unecessary newlines. By supressing whitespace around placeholders and using `nindent` (indent with a new line before the first line) instead of just `indent`, all of these should be addressed.
To test, run `helm template chart/ --set environmentName=master | less`, and look at the beautiful YAML that comes out of it :-)
> SLT-199 prettier helm output

- chart/templates/drupal-service.yaml
- chart/tests/drupal_service_test.yaml
- chart/values.yaml
Fixes #86 
Provides a value to enable/disable ambassador, and allows for ambassador config to be added as values.
Sidenote: 
I'm unsure if the domain annotation on the drupal service should be included only if the ambassador annotation is included. I actually mis-set the domain annotation when using an nginx ingress and it still worked fine, so I'm not sure what its purpose is.
> Make ambassador optional and configurable

- .circleci/config.yml
This has already been pushed to https://github.com/wunderio/silta-circleci for testing. This option is key to support existing projects where Drupal might not be in the repository root.
> SLT-224: Make the drupal root configurable.

- chart/templates/_helpers.tpl
- chart/tests/elasticsearch_test.yaml
- web/sites/default/settings.silta.php
The same way we configure the memcache module when the memcache service is enabled, we can configure elasticsearch_helper when the elasticsearch service is enabled.
> SLT-228: add support for elasticsearch_helper

- .circleci/config.yml
- .dockerignore
It required quite a few iterations to get there, but I'm pretty happy with what we got.
The main change is the introduction of the `build-docker-image` custom CircleCI command which builds and push a specific image, taking a dockerfile location, a path (the docker context) and an id. Before building the image, a hash of the folder that gets copied into the docker image is created and we check the google cloud docker registry for an image with that tag (once the docker 2.0 api is established we can switch over to that) and only build the image if needed.
Now that the entire build and deployment can run in about 1 minute (with a warm cache), it makes more sense to combine both steps into one, saving the time needed to spin up a new docker container, and also avoiding the complexity of …
> SLT-108 skip unnecessary deployments

- chart/templates/elasticsearch-deployment.yaml
Added environment variable to disable X-Pack plugin for Elasticsearch.
Probes were dying as they couldnt query ES container, since it required authentication.
For testing - deploy a release with ES5.x, 6.x - ES container is reachable from drupal php container.
> SLT-240: Disabling X-Pack plugin to allow ES 5.x work

- chart/templates/drupal-deployment.yaml
- chart/templates/post-release.yaml
- chart/tests/drupal_postinstall_test.yaml
- chart/values.yaml
This is a first step towards being able to lower the general resource usage and being able to place more environments in the same cluster while still running everything smoothly. The one place where we need a peak of dedicated resources is for the post-release job, which runs both site installation and configuration imports. Once this one has dedicated resources, we can easily lower the resource utilisation for the always-on pods.
The load tests showed that 500m is about right for a fast installation, more CPU doesn't change much after that.
> SLT-235 dedicated resources for the post-release job

- chart/templates/drupal-deployment.yaml
- chart/values.yaml
I did some testing, and if we have more resources for the post-release job (see https://github.com/wunderio/drupal-project-k8s/pull/99) we can reduce the requested memory for the other containers. 
As discussed in Slack, I would also recommend removing the readiness checks. They are creating a considerable load on the service by themselves and prevent us from being able to lower the resources without the checks failing due to timeouts. They have also been responsible for a few confusing issues for developers, in the end we are better off without them.
Note that the deployment is a bit slower because in this branch the post-release job doesn't yet get additional resources.
> SLT-95 resource optimisation

- .circleci/config.yml
According to https://getcomposer.org/doc/articles/autoloader-optimization.md, this option should always be used in production.
> SLT-242: Optimise the composer autoloader.

- chart/templates/drupal-volumes.yaml
- chart/templates/elasticsearch-deployment.yaml
- chart/values.yaml
Story: https://wunder.atlassian.net/browse/SLT-209
Changes elasticsearch and shell key storage to standard
Related PR in `charts`: https://github.com/wunderio/charts/pull/19
> SLT-209: Do not share shell key and elasticsearch storage

- chart/templates/NOTES.txt
- chart/templates/drupal-service.yaml
- chart/values.yaml
Allows mapping selected domain names (`Values.cexposeDomains`) in ambassador to current deployment.
Proof of concept and branch targetting demo is done in `feature/SLT-256-domains` branch, specifially, this commit:
https://github.com/wunderio/drupal-project-k8s/commit/cd6afae821f3ac3188b9e896f69820b4c5653bed
You should be able to open http://domain-demo.wdr.io/ (delete the domain from DNS zone, please, when You merge this PR).
All available domain names visible in release notes, https://circleci.com/gh/wunderio/drupal-project-k8s/5931
Drupal chart PR: https://github.com/wunderio/charts/pull/26
> SLT-256: loop and expose exposeDomains values

- chart/templates/drupal-configmap-nginx.yaml
- chart/values.yaml
Moving robots.txt rewrite from `silta-cluster` to deployments. Denied by default.
Related PR's: 
- robots.txt nginx rewrite in drupal chart (k8s test): 
https://github.com/wunderio/drupal-project-k8s/pull/111
- Removing ambassador robots.txt mapping from silta-cluster. robots.txt nginx rewrite in drupal and simple charts:
https://github.com/wunderio/charts/pull/27
- Removing robots.txt file from container: 
https://github.com/wunderio/silta-splash/pull/4
> SLT-255: Disallow robots in robots.txt

- chart/templates/_helpers.tpl
- chart/templates/drupal-deployment.yaml
- chart/templates/drupal-volumes.yaml
- chart/tests/drupal_cron_test.yaml
- chart/tests/drupal_postinstall_test.yaml
- chart/tests/private_files_test.yaml
- chart/tests/reference_data_test.yaml
- chart/tests/volumes_test.yaml
- chart/values.yaml
- silta/silta.yml
Dynamic file mounts. File mount is defined by default, can override "mounts" section to add more.
```
mounts:
- name: public-files
storage: 1G
mountPath: /var/www/html/web/sites/default/files
storageClassName: silta-shared
csiDriverName: csi-rclone
- name: private-files
storage: 1G
mountPath: /var/www/html/private
storageClassName: silta-shared
csiDriverName: csi-rclone
readOnly: false
- name: custom-mount
storage: 1G
mountPath: /var/www/html/custom-mount
storageClassName: silta-shared
csiDriverName: csi-rclone
readOnly: false
```
Tests changed accordingly.
No storage migration neccessary - i kept the naming schema `drupal-public-files` and `drupal-private-files` when they are generated. Also, the `PRIVATE_FILES_PATH` env variable also works. All mounts have their env variables now. …
> SLT-203: Dynamic volume generation

- chart/templates/_helpers.tpl
- chart/templates/drupal-configmap-nginx.yaml
- chart/templates/post-release.yaml
- chart/templates/reference-data-cron.yaml
- chart/tests/drupal_cron_test.yaml
- chart/tests/reference_data_test.yaml
- chart/tests/volumes_test.yaml
- chart/values.yaml
- silta/nginx.Dockerfile
- silta/php.Dockerfile
- silta/shell.Dockerfile
The base docker images have been changed so that `/app` is a symlink to `/var/www/html`. Renaming the paths in the chart should work without issues. When all projects have been updated, the symlink will be removed.
> SLT-268: Change the application root to /app.

- silta/silta.yml
The way volumes are specified in silta.yml is now more flexible, and the given example
does not work anymore. See https://github.com/wunderio/charts/blob/master/drupal/values.yaml 
for an example of adding a volume for private files.
The application root within the container is now /app, it is more consistent across different 
types of applications and is also commonly used by other container-based hosting providers.
This pull request was created with https://github.com/wunderio/internal-mass-updater.
> Remove outdated example and fix application root

- chart/templates/drupal-volumes.yaml
- chart/tests/drupal_cron_test.yaml
- chart/tests/drupal_postinstall_test.yaml
- chart/tests/private_files_test.yaml
- chart/tests/reference_data_test.yaml
- chart/tests/volumes_test.yaml
Related issue: https://github.com/wunderio/charts/pull/29
> Only create explicit drupal PVs if using silta-shared storageClassName

- chart/templates/NOTES.txt
- chart/templates/_domains.tpl
- chart/templates/_helpers.tpl
- chart/values.yaml
Installing Drupal automatically often fails with an existing codebase, making it impossible for a deployment to be successful. This PR replaces the automatic installation with some instructions.
The Helm notes now also include instructions on how to import a database dump or importing files into each of the mounted volumes.
See the last step of https://circleci.com/gh/wunderio/drupal-project-k8s/6237 for the result.
> SLT-274: make project migration more intuitive

- chart/templates/post-release.yaml
- chart/tests/reference_data_test.yaml
- chart/values.yaml
We want to be able to skip mounting the reference data volume, but only for branches other than the reference environment. This adds another parameter, which can then be used here: https://github.com/wunderio/silta-circleci/blob/2ca22c3685ed370953858f4cb6c843d5dc0015cd/orb.yml#L422
> SLT-289: Enable to skip mounting reference data volume

- chart/templates/NOTES.txt
- chart/templates/_helpers.tpl
- chart/templates/drupal-deployment.yaml
- chart/templates/drupal-volumes.yaml
- chart/tests/drupal_cron_test.yaml
- chart/tests/drupal_postinstall_test.yaml
- chart/tests/private_files_test.yaml
- chart/tests/reference_data_test.yaml
- chart/tests/volumes_test.yaml
- chart/values.yaml
We use arrays in few places in values.yaml file (cron tasks, whitelisted ip addresses, volume mounts). Helm can iterate over objects, so turning those arrays into objects with arbitrary keys still works the same way. The advantage is that it is then a lot easier to override individual parameters or to add additional items without needing to duplicate the entire array.
> SLT-285: Use objects instead of arrays in silta.yml for easier overrides

- chart/templates/drupal-volumes.yaml
The selector parameter prevents the usage of other storageClasses which might have a dynamic volume driver. Tested in the test/nfs-client-volume branch.
> When using a dynamic provisioner, the pvc should not include a selector.

- chart/templates/drupal-deployment.yaml
- chart/values.yaml
- silta/silta-prod.yml
Steps to test:
The deployment should only have one replica:
```
kubectl get deployment -n drupal-project-k8s drupal-project-k8s--feature-slt-301-drupal
```
Generate some load on the feature branch environment: 
```
siege -c10 --header="Authorization:Basic c2lsdGE6ZGVtbw==" http://feature-slt-301.drupal-project-k8s.silta.wdr.io/
```
Then, while siege is still running check with the first command again to see that the deployment scaled up to 3 replica.
> SLT-301: Enable autoscaling for the Drupal deployment

- chart/templates/drupal-cron.yaml
- chart/templates/drupal-deployment.yaml
- chart/templates/post-release.yaml
- chart/templates/reference-data-cron.yaml
Drush assumes `bash` as the default shell, and `sh` is quite restrictive and has caused a few issues with unsupported syntax.
> SLT-308: Use bash when executing commands in the php container.

- chart/templates/_helpers.tpl
- chart/values.yaml
Many projects have inconsistent paths for the config folder (config, config/sync, sync, drupal_config, etc), and requiring to change that path for a migration could cause issues for existing setups. Making this configurable means we can import those projects without modifications.
> SLT-292: Make the Drupal config path configurable.

- chart/templates/drupal-configmap-nginx.yaml
We ran into an issue where the `fastcgi_buffers` defaults were too low, something that commonly happens with D8 and for which we have an existing configuration in WunderMachina. There are more settings that could be very useful (for example hiding the `x-generator` header), it probably makes sense to have all of them.
> SLT-307: Add fastcgi configuration from WunderMachina.

- chart/templates/drupal-service.yaml
- chart/tests/drupal_service_test.yaml
The v0 API is deprecated (just happened to see an entry in the log), and for what we use the v1 API is compatible.
> SLT-313: Use v1 of the ambassador API.

- chart/values.yaml
We now have the globally installed package as a fallback, so we shouldn't skip reference data if the local package is missing.
> SLT-312: Don't check for a locally installed gdpr-dump package

- chart/templates/_helpers.tpl
- chart/templates/backup-cron.yaml
- chart/templates/backup-volume.yaml
- chart/templates/drupal-cron.yaml
- chart/tests/backup_test.yaml
- chart/values.yaml
- silta/silta-prod.yml
The backup functionality is disabled by default, but I created a test project `test-project-backup` which has backups enabled, and we can see the cron job working, here's the output (edited to show what we would get with older backups):
```
[success] Database dump saved to /backups/2019-08-05-master/db.sql.gz
/backups/2019-08-05-master:
total 4338
-rw-r--r--    1 root     root        4.2M Aug  5 10:49 db.sql.gz
-rw-r--r--    1 root     root       65.0K Aug  5 10:49 public-files.tar.gz
/backups/2019-08-04-master:
total 3798
-rw-r--r--    1 root     root        4.1M Aug  4 10:49 db.sql.gz
-rw-r--r--    1 root     root       65.0K Aug  4 10:49 public-
```
> SLT-109: backup functionality

- chart/files/settings.silta.php
- chart/templates/_helpers.tpl
- chart/values.yaml
- silta/silta-prod.yml
When something is going wrong, especially while setting up new environments, it's a lot more helpful to show errors rather than Drupal's generic message "There was a problem...".
> SLT-321: Show errors by default for dev environments

- chart/templates/_helpers.tpl
- chart/templates/drupal-cron.yaml
- chart/templates/drupal-deployment.yaml
We needed the initContainer to wait for the database when the liveness probe required a running database, but we changed the liveness probe to only check the tcp port, so the initContainer is not needed anymore.
A quick manual test showed that with the initContainer, a pod takes about 30 seconds to respawn when deleted, whereas it took about 10 seconds after this change. This doesn't only affect deployment, but anytime when a pod gets created: upscaling, restarting in case of failure, cluster upgrades, etc.
> Speed up pod creation

- chart/values.yaml
When environments have very low resources, as we set them for development environments, any load easily triggers the autoscaler and memory usage is sufficient to keep the deployment from scaling down.
> Disable autoscale for dev environments

- chart/files/settings.silta.php
- chart/templates/_domains.tpl
- chart/templates/_helpers.tpl
- chart/templates/drupal-configmap-nginx.yaml
- chart/templates/drupal-service.yaml
- chart/templates/varnish-configmap-vcl.yaml
- chart/templates/varnish-deployment.yaml
- chart/templates/varnish-secret.yaml
- chart/tests/drupal_configmap_test.yaml
- chart/tests/drupal_deployment_test.yaml
- chart/tests/drupal_service_test.yaml
- chart/tests/varnish_test.yaml
- chart/values.yaml
- silta/silta.yml
- `VARNISH_ADMIN_HOST`, `VARNISH_ADMIN_PORT` and `VARNISH_CONTROL_KEY` environment variables available in php container when `varnish.enabled` is set to `true`
- Correct `$_SERVER['REMOTE_ADDR']` is set in php headers;
- `Values.nginx.basicauth.noauthips` changed to `Values.nginx.noauthips` to unify nginx and varnish whitelist. This will need a change in existing projects!
- noauthips is also used to control access to cron/install/update pages trough drupal
```
if (req.url ~ "^(|/core)/(cron|install|update)\.php$" && !client.ip ~ internal) {
```
- `Values.nginx.basicauth.realipfrom` changed to `Values.nginx.realipfrom` for the reason mentioned above.
- Ability to define varnish caching backend and size using `Values.varnish.storageBackend`
- Ability to inject custom code into vcl_recv …
> Varnish support

- chart/templates/NOTES.txt
The chart notes always included instructions for the private files, even though they are not enabled by default. This fixes it.
> SLT-329: Only show instructions for enabled mounts.

- .circleci/config.yml
- chart/requirements.lock
- chart/requirements.yaml
- chart/templates/NOTES.txt
- chart/templates/_helpers.tpl
- chart/templates/drupal-configmap-nginx.yaml
- chart/templates/smtp-secret.yaml
- chart/tests/drupal_deployment_test.yaml
- chart/values.yaml
We have ssmtp since it's installed in [amazee.io lagoon php images](https://github.com/amazeeio/lagoon/blob/master/images/php/fpm/Dockerfile#L41). This PR utilizes builtin ssmtp binary and it's custom config to allow sending e-mails from drupal site. 
- Installs mailhog subchart from https://github.com/codecentric/helm-charts/tree/master/charts/mailhog when `.Variables.mailhog.enabled` is set to `true`
- Forwards e-mails to mailhog when `.Variables.mailhog.enabled` is set to `true`
- Allows setting custom smtp relayhost via `.Variables.smtp` value map
- Sets environment values for ssmtp and another set with generic environment variables in case application needs them (we want to avoid relying on ssmtp variables (`SSMTP_MAILHUB`, `SSMTP_USETLS` etc.)
TODO: When we merge this into drupal …
> Sending e-mail

- chart/templates/elasticsearch-deployment.yaml
- chart/values.yaml
The previous resource settings for the Elasticsearch deployment caused it to have too little cpu to be able to properly boot. These settings are now adjusted and the liveness and readiness probes have also been adjusted.
> SLT-278 & SLT-279: Various Elasticsearch fixes

- chart/templates/drupal-cron.yaml
Since these are resources of type CronJob, the `cron` prefix can be skipped without losing information. This solves the problem we have where projects with longer repository names run into issues for feature branches, and should also provide a bit more flexibility with the naming of additional cron jobs.
> SLT-338: Shorten name for cron jobs

- silta/silta-prod.yml
A lowercase 'm' as the memory unit is interpreted as a zero, which results in no dedicated memory. The change has no effect if your project doesn't have a production branch on Silta, but it's good to prevent future issues.
> Kubernetes memory units need to be uppercase.

- chart/templates/_helpers.tpl
- chart/templates/post-release.yaml
- chart/templates/reference-data-cron.yaml
- chart/tests/drupal_postinstall_test.yaml
- chart/tests/reference_data_test.yaml
- chart/values.yaml
- silta/php.Dockerfile
- silta/shell.Dockerfile
- silta/silta.yml
This PR combines a few separate changes which are interrelated:
- Only use gdpr-dump when creating reference data
- Skip the content of cache tables when creating reference data
- Add all mounts to reference data, not just public files
For testing, I made this branch the `referenceEnvironment`, and forked it to a separate branch to test the import (the build is found here: https://circleci.com/gh/wunderio/drupal-project-k8s/7425)
Some follow-up changes:
- Modify gdpr-dump so that it can handle large tables without using a lot of memory.
- Maybe move the gdpr configuration back to a dedicated file. This would work for Drupal 7 since we are not using drush anymore and calling `mysqldump` directly.
- Move gdpr-dump's `mysqldump` to a dedicated command instead of overriding $PATH, so there is …
> Reference data / GDPR refactoring

- chart/templates/drupal-configmap-nginx.yaml
- chart/values.yaml
robots.txt rewrite removed. When the site is not supposed to be accessed, one can set up basic auth.
https://feature-robots.drupal-project-k8s.silta.wdr.io/robots.txt
> Allow robots.txt if the file exists

- chart/templates/drupal-volumes.yaml
- chart/templates/shell-deployment.yaml
- chart/templates/shell-volume.yaml
- chart/tests/private_files_test.yaml
- chart/tests/reference_data_test.yaml
- chart/values.yaml
- The SSH host keys are not affected by read performance, so it's fine to store them in object storage.
- Not using PersistentDisk volumes helps with the limits we are already hitting.
- I used a different volume name, otherwise we would get errors because changing the type of a volume is not allowed.
- A known side effect of this change is that all host keys will be recreated, prompting users to delete the entry in their known_hosts file.
> SLT-409: Use csi-rclone driver for ssh host keys volume

- chart/templates/drupal-configmap.yaml
- chart/tests/drupal_configmap_test.yaml
- chart/values.yaml
This allows having custom configuration (like `location {}`) in server context.
```
nginx:
serverExtraConfig: |
location = /randomlocation {
return 418; 
}
```
Diferrence from `nginx.extraConfig` is that `extraConfig` is mounted as `/etc/nginx/conf.d/misc.conf` and included into `http {}` context. It's used for different purposes.
Frontend chart has this, but slightly different solution - the config block goes above basic auth.
https://github.com/wunderio/charts/blob/master/frontend/templates/configmap.yaml#L102
> Extra config for nginx server context

- chart/Chart.lock
- chart/Chart.yaml
- chart/templates/_overrides.tpl
- Subchart versions are hard-coded, we should only set the minor version (specific versions belong in the lock file).
- There are no major version updates of the underlying updates, but it's still good to keep things up to date.
> SLT-385: Update subcharts for the Drupal chart

- chart/templates/drupal-configmap.yaml
- silta/silta.yml
[nginx map directive](http://nginx.org/en/docs/http/ngx_http_map_module.html) is being leveraged for this task. The list of defined redirects is matched with current url and assigned a variable to custom `$redirect_uri` variable in case it does match. Mapping is done outside of `server` scope, so that full url (with protocol and domain name) can be matched too. Then, the `$redirect_uri` variable is used for actual redirection in `server` scope.
There are following test redirects:
```
nginx:
redirects: |
/test1 / ;
/test2 /test2-redirect ;
http://feature-redirects.drupal-project-k8s.silta.wdr.io/test3 /test3-redirect ;
'://~feature-redirects.drupal-project-k8s.silta.wdr.io/test4$' /test4-redirect ;
~/test5$ /test5-redirect ;
~/test6 /test6-redirect ; …
```
> SLT-382: Custom nginx redirects

- chart/templates/drupal-configmap.yaml
Tested this here: https://feature-configurable-nginx-bod07.drupal-project-k8s.silta.wdr.io/
Uploaded a 37MB file, and it was uploaded successfully.
> Use the php post_max_size for the nginx client_max_body_size for consistency.

- chart/templates/_helpers.tpl
- chart/templates/drupal-configmap.yaml
- chart/tests/drupal_configmap_test.yaml
There's currently a mismatch between the location where we mount our php.ini configuration, and the expected location from the base image. Things still works though, although these configuration files did nothing. This PR fixes the main file with our overrides, removes additional files that were not needed, and also removes unnecessary overrides of the underlying defaults.
We should also revise the remaining overrides. There are some that we probably want to make configurable (like `memory_limit`), and some where we should consider why they should differ from the defaults and document that.
> SLT-460: fix the php.ini location

- chart/templates/_helpers.tpl
- chart/templates/post-release.yaml
- chart/tests/drupal_postinstall_test.yaml
- chart/values.yaml
A project recently ran into issues with large amounts of files and reference data, and we've had issues in general where taking the snapshots was too slow. 
What this changes
- Reference data files are stored as they are, rather than creating a tarball. This enables us to keep existing file, and to just transfer incremental changes.
- Rather than a regexp for files to be excluded, we provide a list of folders that are excluded. This option wasn't used by any project so far. 
- By making the code that imports reference data dynamic, we can remove it from the post-install hook. The post-install command is currently empty, but could be used for things like indexing content into elasticsearch.
- The post-upgrade hook gets run after post-install too, further reducing duplicate code.
Since the …
> Create reference files snapshot with rsync

- chart/templates/shell-deployment.yaml
- chart/templates/shell-secret.yaml
- chart/tests/shell_deployment_test.yaml
Stores gitAuth token  in a secret.
- ssh connection still works;
- Environment variables reference the secret instead of showing it in pod info:
```
PROJECT_NAME:            drupal-project-k8s
ENVIRONMENT_NAME:        feature/gitauth-key-secret
[..]
GITAUTH_API_TOKEN:       <set to the key 'gitAuth.apiToken' in secret 'feature-gitauth-key-secret-secrets-shell'>  Optional: false 
```
> gitAuth key stored in secret

- chart/templates/_helpers.tpl
For our test project there are no perceivable improvement, because we have so few files that the import takes almost no time compared to importing the db dump. The deployment log does show both commands running at the same time though. This should speed things up quite a bit for projects with a lot of content.
> Run database and file import in parallel.

- chart/templates/_helpers.tpl
We recently sped things up by importing files in parallel with the reference database dump, but we can already do that before the database and elasticsearch are ready, and we can also continue while the configuration import and other drush commands are executing.
> Start copying reference data files right away

- charts/drupal/Chart.yaml
- charts/drupal/templates/drupal-deployment.yaml
- charts/drupal/templates/network-policy.yaml
- charts/drupal/templates/shell-deployment.yaml
- charts/drupal/templates/varnish-deployment.yaml
- charts/silta-release/templates/network-policy.yaml
Introduces new label for pods that allow traffic from `silta-cluster` namespace.
Web and shell access works.
> Introducing silta-ingress: allow

- charts/drupal/templates/NOTES.txt
- charts/drupal/templates/_helpers.tpl
Rsync currently triggers errors when transferring a lot of files, of the form: 
```
rsync: mkstemp "/app/web/sites/default/files/.37388109241_7f23737b05_n.jpg.XXXXXX" failed: No such file or directory (2)
```
Adding a local temporary directory should help.
> Use a local temporary directory when rsyncing files.

- charts/drupal/templates/_helpers.tpl
We have an issue with the rsync command that copies the reference data, it takes too long and then the temporary empty folders created by the rclone driver are gone, which results in errors. 
This PR executes separate rsync calls for each subfolder within the mounted volumes. This speeds things up considerably, not only in total, but also from the time it takes from the initial rsync call to the file being created, thus removing the error above.
For testing purposes I added the reference data files from one problematic project to this project, the deployment of a new environment runs in less than 2 minutes.
> Run rsync in parallel for each subfolder

- charts/drupal/templates/drupal-configmap.yaml
The way Drupal uses Twig can cause an excessive number of independent calls to Instana which generates a high CPU activity on our servers.
> SLT-485: Disable Instana Twig instrumentation

- charts/drupal/templates/shell-deployment.yaml
- charts/drupal/values.yaml
It makes sense to have the same resources for the shell containers by default, but when we allocate more cpu for production environment, we don't need to allocate those resources for a container that will be idle most of the time.
> SLT-504: overridable resources for shell container

- charts/drupal/templates/_helpers.tpl
- composer.json
- composer.lock
This came through a happy accident, trying to show output while importing a database dump to avoid CircleCI timeouts due to the lack of output. It turns out that separating the decompressing of the database dump from the piping to `drush sql-cli` speeds things up, which is even increased when using `pv`. 
Unfortunately the output from `pv` doesn't show up in CircleCI, I'll leave that as a separate topic, now that the import is much faster, showing progress is not as critical anymore.
> Speed up database import

- charts/drupal/templates/shell-deployment.yaml
- charts/drupal/templates/shell-secret.yaml
- charts/drupal/tests/shell_deployment_test.yaml
- charts/drupal/values.yaml
- silta/shell.Dockerfile
Merge this into charts repo with caution - the drupal `ssh.Dockerfile` chart uses `drupal-shell:v0.1` while k8s  uses `drupal-shell:latest`. 
This means two things need to be released at the same time:
- `drupal-shell` needs a `v0.1` release tagged from master
- and drupal chart with these changes
- orb needs prefix change for shell image, so the image is rebuilt
> Use keyserver for drupal shell access

- charts/drupal/templates/drupal-ingress.yaml
- charts/drupal/templates/shell-deployment.yaml
The extensions/v1beta1 API is deprecated, and unsupported for Deployment resources starting with kubernetes 1.16. These resources are stateless, replacing them doesn't cause any issues.
> SLT-502: replace deprecated APIs

- charts/drupal/templates/_helpers.tpl
- charts/silta-release/values.schema.json
- charts/silta-release/values.yaml
- silta/silta.yml
When the HTTP proxy is enabled, it is currently used for all HTTP requests made with tools that support these standard environment variables, such as curl. This interferes for example with connecting to the internal elasticsearch service. 
This PR adds some built-in exclusion for internal services called with their full hostname (subdomains of `.svc.cluster.local`), the Elasticsearch service, as well as a configurable list of additional domains.
> Proxy follow-up

- charts/drupal/Chart.lock
- charts/drupal/Chart.yaml
- charts/drupal/templates/_overrides.tpl
Update to version 7.x of the mariadb helm chart. This is a major update and requires the statefulset to be recreated, which is done in https://github.com/wunderio/silta-circleci/pull/103
Updating to the 7.x mariadb helm chart is part of the prerequisites for upgrading to kubernetes 1.16.
> SLT-514: mariadb update

- charts/drupal/templates/drupal-deployment.yaml
This makes no difference for single-zone clusters, but we do get a small benefit with regional clusters.
> Prefer keeping pods in the same zone.

- charts/drupal/templates/shell-deployment.yaml
- charts/drupal/tests/shell_deployment_test.yaml
Link to ticket: https://wunder.atlassian.net/browse/SLT-563
Changes proposed in this PR:
- if drupal backups are enabled, mount the volume containing the backups to the shell deployment as read-only
- add unit test for these changes
How to test:
1. ssh into the feature environment
1. run `ls -l /`, verify you don't see a `backups` directory
1. modify `silta/silta.yml` file and add this to it:
```
backup:
enabled: true
```
1. push this change to a new branch (in order to not mess up this branch)
1. ssh into the new feature environment
1. run `ls -l /`, verify you do see a `backups` directory
1. verify you are not able to write to the directory, as it should be read-only
> SLT-563: Mount backups volume to shell deployment

- charts/drupal/templates/_helpers.tpl
- charts/drupal/values.yaml
Since Drupal 7 projects are using this chart now, the build process might fail when `drush cr` is executed.
Tried several ways to detect major version, even define via `.Values.drupal.majorVersion`, but this seems like the least intrusive one.
> Drupal 7 aware drush commands

- charts/drupal/templates/drupal-configmap.yaml
- silta/php.Dockerfile
FPM config moved out of silta template, so fpm images can have have dedicated config. 
https://github.com/wunderio/drupal-php-fpm/commit/6df24f5dcf0b11035589c002ecf6c57acb81b3b8
https://github.com/wunderio/silta-images/commit/ab9930bd75e2b3343c4418e0955859f92cfd8e29
Config is embedded into container, verified by viewing `/usr/local/etc/php-fpm.d/w-php-defaults.conf` in drupal/php container
> Some FPM config moved to Docker container

- charts/drupal/values.yaml
- silta/silta.yml
Our deployments receive a steady flow of mailhog log messages that are normally irrelevant (because it just works) and it generates unnecessary noise. We use [mailhog chart by codecentric](https://github.com/codecentric/helm-charts/tree/master/charts/mailhog) to deploy mailhog, but [there's no way to suppress logs](https://github.com/codecentric/helm-charts/pull/272) other than overriding entrypoint currently. Our solution to this is to replace entrypoint in the Docker image and overriding the image source in helm chart.
Entrypoint override:
https://github.com/wunderio/silta-images/blob/master/silta-mailhog/silent/Dockerfile#L3
If one still wants to see mailhog logs for some reason, he can reset/override `.Values.mailhog.image.repository` and `.Values.mailhog.image.tag` variables.
> Mailhog log suppression

- charts/drupal/templates/solr-statefulset.yaml
- charts/drupal/values.yaml
- silta/silta.yml
removes default `storageClassName`, falls back to standard for gke cluster type, otherwise upgrade for existing deployments fail with
> Error: UPGRADE FAILED: cannot patch "feature-storageclassname-solr" with kind StatefulSet: StatefulSet.apps "feature-storageclassname-solr" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
Not setting `storageClassName` for new deployments uses cluster's default storageclass.
> Feature/aws cluster/storageclassname

- charts/drupal/templates/drupal-cron.yaml
- silta/silta.yml
Trims cronjob to fit DNS spec name length, while also having a unique identifier at the end of resources name.
> SLT-602: Trim cronjob names

- charts/drupal/values.yaml
Changes proposed in this PR:
- reorder the default postupgrade commands in Drupal chart so that cache rebuild is the very first command being run
- apparently my IDE removed a bunch of whitespaces as well
So before the order of commands was:
1. drush status
2. drush cache-clear all OR drush cache-rebuild
3. drush updatedb
4. drush config-import
5. drush cache-rebuild
After this PR, the order will be:
1. drush cache-clear all OR drush cache-rebuild
2. drush status
3. drush updatedb
4. drush config-import
5. drush cache-rebuild
Link to Slack discussion: https://wunder.slack.com/archives/C8UN6AG9W/p1616578842088100
> Drupal chart: Fix failing postupgrade drush commands

- charts/drupal/values.yaml
Memcache chart has been changed from Kubernetes stable to Bitnami (https://github.com/wunderio/drupal-project-k8s/commit/735d7e242e93484712fd0a5aef1d87e2bc5652e7) but the configurations to comply with Bitnami chart wasn't updated.
This pull request updates the memcached maxMemorySize from `memcached.maxItemMemory` to be passed as command argument. An alternative option to pass the maxMemorySize would have been to use `extraEnv` and set the `MEMCACHED_CACHE_SIZE` like this:
```
extraEnv:
- name: MEMCACHED_CACHE_SIZE
- value: "118"
```
Using environment variables however doesn't allow setting some other configuration variables such as `maxItemSize` which must be provided as a command line argument. So if we want to set both the `arguments` option is more simple solution.
How to test:
1. …
> Pass maxMemoryLimit and maxItemSize as command arguments to memcached.

- charts/drupal/templates/varnish-deployment.yaml
- charts/drupal/tests/varnish_test.yaml
- charts/drupal/values.yaml
Allows defining custom parameters for varnishd.
Related image adjustment: https://github.com/wunderio/silta-images/commit/198370953d50325259945c40c447acef1114c9e8
```
varnish:
enabled: true
extraParams: "-p http_resp_hdr_len=65536 -p http_resp_size=98304"
```
> Allow passing extra parameters for varnishd

- charts/drupal/templates/varnish-configmap-vcl.yaml
- charts/drupal/values.yaml
Bonus: Increase default varnish probe timeout to 5s to hopefully avoid 503s under high load.
> Make varnish backend config configurable

- charts/drupal/templates/drupal-certificate.yaml
- charts/drupal/templates/drupal-ingress.yaml
- silta/silta.yml
Ensure the test domain is using the provided existing secret.
Note: the existing secret doesn't have valid cert.
Reminder to self: remove test domain from silta.yaml
> Support for existing TLS secrets.

- charts/drupal/templates/_helpers.tpl
- charts/drupal/values.yaml
In case the storage backend filesystem is already backed up there is no need to take extra backups of files.
> Allow skipping files backup.

- charts/drupal/templates/_helpers.tpl
- charts/drupal/templates/drupal-configmap.yaml
- charts/drupal/templates/drupal-cron.yaml
- charts/drupal/test.values.yaml
- charts/drupal/values.schema.json
- charts/drupal/values.yaml
When running production on 3rd party hosting for example in Acquia cloud the Drupal installation path needs to be different from our standard `/web`.
We could move the `docroot` path under `/app/web` when building the image, but there are also dependencies on that folder e.g. in `composer.json`.
Related PR: https://github.com/wunderio/silta-circleci/pull/137
> Make Drupal installation path configurable.

- charts/drupal/templates/drupal-configmap.yaml
Added suggested mitigations # 1 and # 4 from https://hexadix.com/slowloris-dos-attack-mitigation-nginx-web-server/
Other limits were already appropriate.
> Increase worker_connections and worker_rlimit_nofile.

- charts/drupal/templates/drupal-configmap.yaml
UA exceptions still work:
```
curl -H "User-Agent: test"   https://feature-hc-ua-context.drupal-project-k8s.dev.wdr.io/abc -I
HTTP/2 401 
curl -H "User-Agent: GoogleHC/1.0"   https://feature-hc-ua-context.drupal-project-k8s.dev.wdr.io/abc -I
HTTP/2 200 
```
> Moving hc_ua to a different context for openresty compatability

- charts/drupal/templates/drupal-configmap.yaml
- silta/silta.yml
- Limits retry to css and js aggregation folders to prevent delay on derivatives
- Passing final 404 to @drupal as fallback
> fs retry fixes

- charts/drupal/templates/drupal-configmap.yaml
- charts/drupal/templates/varnish-configmap-vcl.yaml
- charts/drupal/tests/drupal_configmap_test.yaml
- charts/drupal/tests/shell_deployment_test.yaml
- charts/drupal/values.schema.json
- charts/drupal/values.yaml
- silta/silta.yml
Allows having multivalue `nginx.realipfrom` list (map). 
Existing deployments overriding `nginx.realipfrom` might get notice, that will be removed after they change the configuration structure. The message (warning) won't affect deployment, it still works as expected and does override the default value.
```
coalesce.go:196: warning: cannot overwrite table with non table for realipfrom (map[gke-internal:10.0.0.0/8])
```
> Multivalue nginx.realipfrom

- charts/drupal/Chart.yaml
- charts/drupal/templates/drupal-certificate.yaml
- silta/silta.yml
Solves issue where cert-manager creates an extra ingress for well-known validation path which does not play nicely with gcs type ingress.
Possibly related issue: https://github.com/jetstack/cert-manager/issues/2538#issuecomment-922901920
> Ingress tls test

- charts/drupal/templates/drupal-ingress.yaml
GCP ingress returns following 
> TLS entry 0 is invalid: secret "feature-sticky-sessions-tls-sticky" for ingress TLS has no hosts specified
It seems to be related to this issue: `https://github.com/cert-manager/website/issues/475`
Ingress TLS documentation:
https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
> tls hosts definition for ingress resources

- charts/drupal/templates/drupal-configmap.yaml
- charts/drupal/values.yaml
- silta/silta.yml
- Allows custom locations for retry404s. 
- Deprecates old configuration schema (with failure message)
Old configuration syntax:
```
nginx:
retry404s: 5
```
New configuration syntax:
```
nginx:
retry404s:
delay: 5
paths:
- "^/sites/(.*)/files/(?:css|js)/(.*).(?:css|js)$"
- "^/sites/(.*)/files/(.*).(?:png|jpg)$"
```
> Allows custom locations for retry404s. Deprecates old configuration schema

- charts/elasticsearch/templates/statefulset.yaml
- silta/silta.yml
#https://github.com/elastic/helm-charts/commit/4e31e0cf3d025f9ce877ac52d218f49d72e26447
Excerpt:
```
..Updating the keystore initContainer to also use bash instead of sh. This is required for
Elasticsearch > 7.16.0 because the Docker image is now based on Ubuntu
instead of CentOS 8, and sh on Ubuntu isn't compatible with the
`if [[... -eq ... ]]` statements.
```
> Use bash for initContainers

- charts/drupal/Chart.yaml
- charts/drupal/templates/solr-statefulset.yaml
- charts/drupal/values.yaml
- silta/silta.yml
Temporary switching to forked solr 8 image [with CVE-2021-44228 and CVE 2021-45046 mitigation](https://github.com/wunderio/silta-images/commit/9060b7eb2e9431434a718311fe4e02a8b0f1c859)
> Testing forked solr 8 image

- charts/drupal/templates/drupal-configmap.yaml
- charts/drupal/tests/drupal_configmap_test.yaml
- charts/drupal/values.yaml
tip: remove security headers by setting `nginx.security_headers: ""`
> Allow security header customization

- charts/drupal/templates/_helpers.tpl
- charts/drupal/tests/drupal_ingress_test.yaml
`semverCompare` seems to have some consistency issues, so we'll just check if api is present.
> apiVersion conditionals adjustment

- charts/drupal/values.yaml
Helps debugging cases when db crashes due to full storage.
> Print mariadb disc usage before db service boot

- charts/drupal/files/settings.silta.php
Added a bit of php for `settings.php` to enable Drupal Ping to survey the Elasticsearch connection.
https://github.com/wunderio/drupal-ping#elasticsearch
Not sure if relevant, but here are more details about the implementation details, why this is separate variable.
https://wunder.slack.com/archives/C54RM7G4F/p1648463185202509
I'm not sure how to test this properly.
Copied the relevant code to one of my current projects, and ping recognized the connection and tested positive.
Not sure about adding automated tests.
> Enable Elastichsearch pinging by Drupal Ping

- charts/drupal/Chart.lock
- charts/drupal/Chart.yaml
- silta/silta.yml
Mailhog chart upgrade. Tested, works. Includes mailhog chart release that fixes unset replica issue (`https://github.com/codecentric/helm-charts/pull/626`). It caused downscaled mailhog instances to stay at `replicas: 0` even after redeployment since mailhog resource did not define `replicas: 1`.
> Mailhog chart upgrade

- .circleci/config.yml
- charts/drupal/values.yaml
- silta/nginx.Dockerfile
- silta/php.Dockerfile
- silta/shell.Dockerfile
Silta docker container images are being migrated from [Google Container Registry](https://eu.gcr.io/silta-images/) to [Docker Hub](https://hub.docker.com/u/wunderio).
This PR changes base image location to the new image registry and adjusts some image names.
Please review adjusted image paths and make sure this PR only changes relevant configuration files.
This pull request was created with https://github.com/wunderio/internal-mass-updater.
> Silta container base image migration to Docker Hub

- charts/drupal/templates/drupal-certificate.yaml
- silta/silta.yml
How I tested:
addded to silta.yml 
```
domainPrefixes: ['en', 'fi', 'ee', 'lv']
ssl:
enabled: true
issuer: selfsigned
```
Made sure that Certificates and secrets are created for domains with prefixes.
> Domain prefixes for custom and selfsigned SSL certificates

- charts/drupal/templates/_helpers.tpl
**Changes proposed:**
- Append the drupal backup tar command in order to ignore tar exit code 1
**Reasoning:**
I noticed the backup cron job to fail multiple times, and the last line in logs was `backup tar: /app/web/sites/default/files: file changed as we read it`.
If any files change while tar is creating an archive, it will exit with code 1 and the rest of the backup job will not get run.
From [tar docs](https://www.gnu.org/software/tar/manual/html_section/Synopsis.html): 
> If tar was given ‘--create’, ‘--append’ or ‘--update’ option, this exit code [1] means that some files were changed while being archived and so the resulting archive does not contain the exact copy of the file set.
Changes are based on https://stackoverflow.com/a/49112839/12416374
> Improve file backup job to ignore tar warnings

- charts/drupal/templates/_helpers.tpl
Database import takes an hour or more. But I as a user don't know if it is 5min or more.
`pv` command is already in the code, but it is useless, as it does not provide any output because it is not running on an active terminal. The `-f` flag forces `pv` to produce output, and that could be seen in the CircleCI task while importing the database.
I don't know how to test this, but I assume Silta guys know how.
> Make `pv` output visible when importing reference database.

- charts/drupal/templates/drupal-configmap.yaml
- charts/drupal/values.yaml
Reverts https://github.com/wunderio/drupal-project-k8s/pull/393
> Reenabling gdpr-dump. Requires php images to support it.

- charts/drupal/templates/_helpers.tpl
- Update drupal.extract-reference-data so that it exports one .sql file per database table, and saves them in db.tar.gz
- Update drupal.import-reference-db so that it supports importing the database from db.tar.gz, using xargs to run 10 simultaneous mysql commands, making the import roughly 60% faster than previously
- Keep backwards compability so that the older way of importing db.sql.gz still works
- Improve bash code style
**Note: The new way of importing reference database might consume more memory, so if pods get OOMKilled while importing, the mariadb memory limit needs to be increased.**
**Note 2: Any scripts or commands that developers have used for fetching the reference database manually will need to be updated.**
> Faster way of exporting and importing reference database for Drupal chart

- charts/drupal/Chart.lock
- charts/drupal/Chart.yaml
Current Redis subchart is not hosted on remote repository anymore. This upgrades to latest available from 16.x branch.
> Redis chart update to latest available 16.x

- charts/drupal/templates/drupal-deployment.yaml
-- 
php-fpm configuration file (/tmp/zz-custom.conf -> /usr/local/etc/php-fpm.d/zz-custom.conf) is copied in php container init scripts now.
> php-fpm configuration file is copied in php container init scripts now

- charts/drupal/files/settings.silta.php
- charts/drupal/files/silta.services.yml
Monolog is not included in CLI (cron commands) and we do not get cron logs in Sumo
Currently, this is due to `silta.services.yml` being excluded in `settings.silta.php`
```
/**
* Use our own services override.
*
* We don't include this when running on CLI, for example when using Drush,
* because the output from monolog to stdout interferes with the Drush batch
* processing, causing the process to die when the Drush tries to start a new batch.
*/
if (PHP_SAPI !== 'cli') {
$settings['container_yamls'][] = 'sites/default/silta.services.yml';
}
```
Get the Drupal cron messages in Sumo.
Use stderr instead of stdout
This was first discussed in this PR  https://github.com/wunderio/drupal-project-k8s/pull/560
Also added the Default log level of DEBUG so it is more visible
and changed the name of …
> Log to STDERR instead of STDOUT with monolog 

- charts/drupal/templates/drupal-ingress.yaml
- charts/drupal/values.yaml
- silta/silta-test.yml
- Adds nginx ingress annotations to default configuration (allows switching out traefik ingress while keeping the same name):
- http->https redirect abstraction
- rate limits
- Adds downscaler annotation to `exposeDomains`, allowing wakeup via `exposeDomain` entries
Once reviewed, test domain entries will be removed.
> Feature/test cluster/nginx ingress

- charts/drupal/templates/drupal-deployment.yaml
- Adds an identical preStop hook to the php container as we have in the nginx container
- Increase the sleep time in nginx and php preStop hooks in order to prevent errors as much as possible. This was tested with different settings, and for now 15s seemed good.
Related PR: https://github.com/wunderio/charts/pull/368
Related previous PR that did not get merged: https://github.com/wunderio/charts/pull/309
> SLT-846: 15s sleep in preStop hooks for php and nginx container

- charts/drupal/templates/_helpers.tpl
- silta/silta.yml
Secrets can be referenced as environment variables for PHP containers.
1. Create a secret `kubectl create secret generic secret-resource --from-literal=somefield=somedata -n drupal-project-k8s`
2. Add a sample config for env vars in `silta.yml`
```
php:
env:
TESTING: testval
secret_TEST:
valueFrom:
secretKeyRef:
name: secret-resource
key: somefield
```
4. After deployment, exec into PHP container. There should be 2 environment variables added:
`TESTING`, with a value from `silta.yml`
`secret_TEST`, with a value defined in secret `secret-resource`, from a field `somefield`
> Support for secrets as environment variables

- charts/drupal/templates/_helpers.tpl
- charts/drupal/tests/drupal_php_env_test.yaml
These changes should allow projects to set `DRUSH_OPTIONS_URI` PHP environment variable without causing deployment error.
If `DRUSH_OPTIONS_URI` is not set, the output manifest should remain with the default/fallback value which uses `drupal.domain` value.
Note: I'm uncertain of how to test this locally, so I wish that someone is able to actually run these changes and confirm them working.
> SLT-855: Allow DRUSH_OPTIONS_URI override

- charts/drupal/templates/drupal-configmap.yaml
In Drupal 10.1 Aggregation has been changed 
Now we should pass the css/js request to drupal
https://www.drupal.org/node/2888767
https://www.drupal.org/node/3301716
The code change provided in the above Drupal org pages does not take into account the langcode that may be in the Url.
the proposed code is from Lando D10 nginx conf :) 
https://github.com/lando/drupal/blob/c787282143af609482369efa135e2ad7c0c9d64a/recipes/drupal10/default.conf.tpl#L99
> Forward js and css to drupal in nginx

- charts/drupal/values.yaml
tested: installing 10.3, upgrading to 10.6. Also, doing a clean 10.6 install. No issues met.
> SLT-883: Upgrade default Maria DB version to 10.6

- .circleci/config.yml
- silta/silta-master.yml
- silta/silta-prod.yml
- silta/silta.yml
- Adds a new silta-master.yml, which will be used in master env
- Defines new default cron schedules separately for feature envs, master env and production env. The point here is to have cron jobs run very seldomly in feature envs unless specifically needed to run more frequently.
- Refactor circleci config by using more anchors, adding more comments and removing references to obsolete branches
If accepted, these changes will also be made to the drupal-project template.
> SLT-898: Redefine default cron schedules for different envs

- charts/drupal/values.yaml
When running tests with the latest helm release, it fails deployment with following error
> Error: INSTALLATION FAILED: template: drupal/charts/redis/templates/sentinel/hpa.yaml:1:18: executing "drupal/charts/redis/templates/sentinel/hpa.yaml" at <.Values.replica.autoscaling.enabled>: nil pointer evaluating interface {}.autoscaling
This pr sets `replica.autoscaling.enabled` value.
> Fix for redis hpa resource error

- .circleci/config.yml
- silta/php.Dockerfile
- silta/shell.Dockerfile
While 8.0 still works, it does complain about drupal compatibility.
> [warning] Your PHP installation is too old. Drupal requires at least PHP /8.1/. It is  recommended to upgrade to PHP version /8.1.6/ or higher for the best ongoing support. See PHP's version support documentation [1] and the Drupal PHP requirements [2] page for more information.
> [1] http://php.net/supported-versions.php
> [2] https://www.drupal.org/docs/system-requirements/php-requirements
> (Currently using PHP 8.0.30)
> [success] No pending updates.
This pr uses php 8.2 for project.
> Update drupal-project-k8s to use php 8.2

- charts/drupal/templates/backup-cron.yaml
- charts/drupal/templates/backup-volume.yaml
- charts/drupal/templates/shell-deployment.yaml
- charts/drupal/tests/shell_deployment_test.yaml
- silta/silta.yml
This sets [vfs-cache-mode](https://rclone.org/commands/rclone_mount/#vfs-file-caching) to off for silta-shared backup pvc mounts and changes pvc & pv names to avoid immutable field issue with existing deployments.
Should solve backup unreliability issue where rclone process is stopped before it has fully copied file from .cache folder to remote.
Testing:
```yaml
backup:
enabled: true
schedule: '0 * * * *'
retention: 2
```
> Set vfs-cache-mode to "off" for backup volumes

- charts/drupal/templates/_helpers.tpl
- charts/drupal/templates/backup-cron.yaml
- charts/drupal/templates/drupal-cron.yaml
- charts/drupal/templates/drupal-deployment.yaml
- charts/drupal/templates/reference-data-cron.yaml
- charts/drupal/tests/drupal_cron_test.yaml
- charts/drupal/tests/drupal_deployment_test.yaml
- charts/drupal/values.schema.json
- charts/drupal/values.yaml
Allows setting timezone for cronjobs ([beta since 1.25](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#time-zones)) and TZ environment variables for nginx and php related pods (shell, drupal, referenceData, backups, cronjobs).
TZ environment variable will work only when tzdata package is added. No errors will occur if the package is absent.
https://github.com/wunderio/silta-images/pull/170
https://github.com/wunderio/silta-images/pull/171
Value is empty by default so it won't affect existing deployments but enables them to do so.
> Timezone support

- charts/drupal/templates/drupal-configmap.yaml
- charts/drupal/values.schema.json
- charts/drupal/values.yaml
- silta/silta.yml
In case there is a need to increase PHP's `max_execution_time` value the current implementation doesn't have any effect unless `client_body_timeout` / `client_header_timeout` in nginx config are also adjusted accordingly.
This allows both to override these values and keep them in sync with `max_execution_time` while keeping the current default of `60` seconds.
> Sync nginx client_header_timeout and client_body_timeout with php max_execution_time

- charts/drupal/templates/drupal-configmap.yaml
Previous approach allowed to bypass header from CDN in some scenarious. 
To not to mess with values and exposed hostnames test environment is created under 
feature/expose-fastly-domain branch
Hostname: 
drupal-project-k8s-staging.fastly.wdr.io
You can wake it up and check direct URL with
silta ci release wakeup --namespace drupal-project-k8s --release-name feature-expose-fastly-domain
> Mapping var, server block for proxy auth header

- charts/drupal/templates/drupal-cron.yaml
- charts/drupal/tests/drupal_cron_test.yaml
- charts/drupal/values.schema.json
- charts/drupal/values.yaml
Allows setting cronjob defaults like resources or nodeselector. This PR also updates the inheritance logic used for assigning resource definitions for cronjobs, so that it works in the same way as it does in the frontend chart.
> SLT-901: Added cronjob defaults and updated cronjob resource inheritance logic

- charts/drupal/files/settings.silta.php
- charts/drupal/templates/_helpers.tpl
- charts/drupal/templates/clamav-configmap.yaml
- charts/drupal/templates/clamav-deployment.yaml
- charts/drupal/templates/clamav-service.yaml
- charts/drupal/values.schema.json
- charts/drupal/values.yaml
- composer.json
- composer.lock
- silta/silta.yml
- Implements deployment (pod) with two containers - clamd and freshclam
- Freshclam runs in daemon mode that updates virus signatures 2 times per day (`Checks` configuration parameter). Freshclam is run in daemon mode instead of cronjob so that virus signatures are shared with clamd.
- Adds clamd connection parameters (`CLAMAV_HOST`, `CLAMAV_PORT`) to drupal/php and shell containers.
- Injects clamav module configuration in settings.silta.php when clamav is enabled in silta settings.
- Allows image and resource and freshclam configuration overrides
**Testing / Usage:**
1. Enable clamav in silta settings: `clamav.enabled: true`
2. Install clamav drupal module (`composer require 'drupal/clamav:^2.0'`) and enable it.
3. Clamav status should be available in drupal status page.
4. Download …
> SLT-1034: ClamAV

- .circleci/config.yml
- charts/drupal/templates/backup-cron.yaml
- charts/drupal/templates/varnish-deployment.yaml
- charts/drupal/tests/db_test.yaml
- charts/drupal/tests/drupal_cache_tags_test.yaml
- charts/drupal/tests/drupal_cron_test.yaml
- charts/drupal/tests/drupal_deployment_test.yaml
- charts/drupal/tests/drupal_hpa_test.yaml
- charts/drupal/tests/drupal_ingress_test.yaml
- charts/drupal/tests/drupal_node_selector_test.yaml
- charts/drupal/tests/drupal_php_env_test.yaml
- charts/drupal/tests/elasticsearch_test.yaml
- charts/drupal/tests/memcached_test.yaml
- charts/drupal/tests/nginx-extra-config_test.yaml
- charts/drupal/tests/private_docker_image_test.yaml
- charts/drupal/tests/private_files_test.yaml
- charts/drupal/tests/redis_test.yaml
- charts/drupal/tests/reference_data_test.yaml
- charts/drupal/tests/shell_configmap_test.yaml
- charts/drupal/tests/shell_deployment_test.yaml
- charts/drupal/tests/varnish_test.yaml
- Update helm unit tests to work with latest version of the helm-unittest plugin
- Fix two bugs with duplicate keys in drupal-cron.yaml and varnish-deployment.yaml, reported by the updated tests
> SLT-1026: Update helm unit tests to work with latest version of the helm-unittest plugin

- charts/drupal/templates/_helpers.tpl
- charts/drupal/templates/backup-cron.yaml
- charts/drupal/templates/backup-volume.yaml
- charts/drupal/templates/drupal-volumes.yaml
- charts/drupal/templates/post-release.yaml
- charts/drupal/templates/reference-data-cron.yaml
- charts/drupal/templates/shell-deployment.yaml
- charts/drupal/templates/shell-volume.yaml
- charts/drupal/tests/drupal_cron_test.yaml
- charts/drupal/tests/drupal_postinstall_test.yaml
- charts/drupal/tests/private_files_test.yaml
- charts/drupal/tests/reference_data_test.yaml
Changes:
- Skips silta-shared PV creation when provisioner is available, removes selector field from silta-shared PVC's
- PVC name change for silta-shared storageclass PVC's to avoid immutable field update errors
- Reference data PVC lookup (lookup and use the new PVC when found)
Testing:
a1: Make a new branch off master, deploy it to cluster with updated storage driver.
a2: Store some files
a3: Merge this branch into it, deploy, see if files are still present. PVC name should end with "2"
b1: Make a new branch off master, change storageclass to something else, deploy it to cluster with updated storage driver.
b2: Store some files
b3: Merge this branch into it, see if files are still present. Validate PVC name, it should not end with "2"
Do the same on a cluster without csi rclone update, …
> silta-shared PV adjustments for new csi-rclone provisioner

- charts/drupal/templates/post-release.yaml
- charts/drupal/tests/reference_data_test.yaml
Always use new reference data pvc name when current environment is the reference environment
> always use new pvc when current environment is reference environment

- charts/drupal/values.yaml
Link to ticket: https://wunder.atlassian.net/browse/WNDR-281
- Pin only major and minor version of mariadb so that we get patch updates automatically
- Also use debian 12 instead of 11 since new patch updates for mariadb come only to debian 12
> WNDR-281: Unpin patch version of mariadb, pin only major.minor versions.

- charts/drupal/templates/_helpers.tpl
- Add flag --delete-excluded to the rsync command when extracting reference data files
How to test:
- In a projects main env, create a test file at web/sites/default/files/ref-test/foobar
- Trigger the cronjob for generating reference data
- Verify that the test file exists in the reference data
- Add "ref-test" to referenceData.ignoreFolders
- Trigger the cronjob for generating reference data
- Verify that the test file no longer exists in the reference data
> When extracting reference data files, ignoredFolders do not get deleted

- charts/drupal/templates/drupal-cron.yaml
- Add the name (key) of the cronjob as a label. This is helpful when dealing with multiple cronjobs that have shortened/hashed names
> Add cronjob name as label

- charts/drupal/templates/backup-cron.yaml
- charts/drupal/values.schema.json
- charts/drupal/values.yaml
- Add nodeSelector support for backup jobs
- Set the default value to an empty object
Here are screenshots from test:
**Backups enabled, using default value for nodeSelector:**
**Backups enabled, using overridden value for nodeSelector:**
> Add nodeSelector support for backup jobs

- charts/drupal/templates/_helpers.tpl
- charts/drupal/templates/backup-cron.yaml
- charts/drupal/templates/clamav-deployment.yaml
- charts/drupal/templates/drupal-cron.yaml
- charts/drupal/templates/drupal-deployment.yaml
- charts/drupal/templates/post-release.yaml
- charts/drupal/templates/reference-data-cron.yaml
- charts/drupal/templates/serviceaccount.yaml
- charts/drupal/templates/shell-deployment.yaml
- charts/drupal/templates/silta-hub.yaml
- charts/drupal/templates/solr-statefulset.yaml
- charts/drupal/templates/varnish-deployment.yaml
- charts/drupal/tests/private_docker_image_test.yaml
- charts/drupal/tests/serviceaccount_test.yaml
- charts/drupal/values.schema.json
- charts/drupal/values.yaml
- Dedicated serviceaccount for most pods
- Disable automounting SA tokens
> pod SA, disable automount SA tokens

- charts/drupal/values.yaml
Motivation
--
- Current gdprDump config for user_field_data.name field doesn't check the uniques of the generated value, thus it can lead to entries with duplicate "names". That is against Drupal user_field_data DB table/index rules (see below) and would lead to errors in reference DB import, thus missing data.
This issue can present itself on large sites with thousands of users (i.e., 35k) as there is a hight change of gdprDump generating entries with duplicate usernames as I believe those are not completely randomized but rather generated from a given set of "names", "surnames", "titles" etc.
- Make sure unique usernames are generated by gdprDump by explicitly setting `unique: true` property
> SLT-1164: Make sure gdprDump generates unique usernames in user_field_data

- charts/drupal/files/silta.services.yml
Adjust the default monolog channel handler:
- set formater to JSON to have structured Drupal logs
- specify default log processors
- override monolog's filter_backtrace processor to remove redundant log data which makes sense in Drupal UI but not on stderr
> SLT-1136: Drupal chart: Use JSON as the default formatter for application logs when handled by monolog

- .circleci/config.yml
- charts/drupal/Chart.lock
- charts/drupal/Chart.yaml
- charts/drupal/templates/NOTES.txt
- charts/drupal/templates/_helpers.tpl
- charts/drupal/templates/checks.yaml
- charts/drupal/templates/drupal-configmap.yaml
- charts/drupal/templates/smtp-secret.yaml
- charts/drupal/templates/varnish-configmap-vcl.yaml
- charts/drupal/test.values.yaml
- charts/drupal/tests/drupal_deployment_test.yaml
- charts/drupal/values.schema.json
- charts/drupal/values.yaml
- silta/silta.yml
**Motivation:**
[Mailhog](https://github.com/mailhog/MailHog) is an email service we’re using in our development environments (local & Silta non-production) to test out if email functionalities are working properly. Mailhog [is not maintained anymore](https://github.com/mailhog/MailHog/issues/442#issuecomment-1493415258) and is causing issues for developers. Therefore, we need to replace it with some alternative. Our current pick is [Mailpit](https://mailpit.axllent.org/).
- Add mailpit dependency, enable it, add default value overrides
- Update chart templates with needed changes for mailpit to work
- Update unit tests to run against mailpit instead of mailhog
- Keep mailhog in chart but add deprecation notices
How to test:
1. Install the updated chart and see that …
> SLT-1103: Drupal chart: Add support for mailpit, deprecate mailhog

- charts/drupal/templates/_helpers.tpl
- charts/drupal/values.schema.json
- charts/drupal/values.yaml
This pull request introduces a new feature to configure the database import method for reference data in the Drupal Helm chart. It allows users to choose between parallel and sequential import methods, enhancing flexibility and performance. The changes also include validation for the new configuration and error handling during the import process.
* **Import Method Implementation in `_helpers.tpl`:** Added logic to support two database import methods (`parallel` and `sequential`) based on the `referenceData.databaseImportMethod` configuration. Includes error handling to ensure failed imports are reported and logged.
* **Schema Update in `values.schema.json`:** Added a new property, `databaseImportMethod`, to the schema definition to validate the configuration.
* **Default Configuration in …
> Make reference database import method configurable.

- charts/drupal/templates/NOTES.txt
Drupal chart: 
- Generate sql dump-file name as well as the local file mount folder names in release notes using `namespace` and `release-name`. This can prevent accidental cross-namespace or cross-environment imports.
- Ensure that the mount path in **download** command is suffixed with a slash to download contents of the mount not the folder itself, this retains the right folder structure when uploading files with **upload/import** command (i.e, doesn't create an extra sub-directory).
How to test:
1. Can be tested by using commands from release notes here: https://app.circleci.com/pipelines/github/wunderio/drupal-project-k8s?branch=feature%2FSLT-1037-sql-dump-name (or you can preview the release notes locally by running `helm install --dry-run test-release …
> SLT-1037: Drupal chart: Change default names in helm release notes

- charts/drupal/values.yaml
Fixes notice:
> "coalesce.go:286: warning: cannot overwrite table with non table for drupal.memcached.tolerations (map[])"
Related to `https://github.com/bitnami/charts/pull/6265`
> Fixes memcached.tolerations notice

- silta/php.Dockerfile.dockerignore
- silta/shell.Dockerfile.dockerignore
This pull request makes a minor update to the `.dockerignore` files for the Silta project. The change removes the exclusion of Silta Dockerfile and Dockerfile.dockerignore patterns, which may affect which files are ignored during Docker builds.
- Removed the lines ignoring `silta/*.Dockerfile` and `silta/*.Dockerfile.dockerignore` from both `silta/php.Dockerfile.dockerignore` and `silta/shell.Dockerfile.dockerignore` files.
> Update .dockerignore files

- charts/drupal/templates/backup-cron.yaml
Uses same mariadb image for backup validation task as the actual service
> mariadb backup validation image

- .lando.yml
- README.md
- charts/drupal/values.yaml
- docs/README.md
- docs/SLT-968-gdpr-dump-randomizetext-implementation.md
- grumphp.yml
- phpstan.neon
- phpunit.xml
- web/modules/custom/testing_utilities/README.md
- web/modules/custom/testing_utilities/config/gdpr-dump.yaml
- web/modules/custom/testing_utilities/testing_utilities.info.yml
- web/modules/custom/testing_utilities/tests/src/Functional/GdprDumpExecutionTest.php
- web/modules/custom/testing_utilities/tests/src/Kernel/GdprDumpConfigurationTest.php
- web/modules/custom/testing_utilities/tests/src/Unit/GdprDumpConfigValidatorTest.php
Fixes the issue where GDPR sanitization doesn't create unique names and therefore causes random deployment failures.
- 315fcd7 ci(SLT-968): Disable PHPUnit in GrumPHP until database setup is configured
- e05cb3b docs(SLT-968): Remove reference to internal AI rules directory
- f825fde fix(SLT-968): Improve PHPUnit test coverage in GrumPHP configuration  
- 7b6c44c fix(SLT-968): Resolve GDPR sanitization deployment failures with unique name generation
- **Replaced faker with randomizeText converter** in `charts/drupal/values.yaml` to guarantee unique name generation
- **Eliminated random deployment failures** caused by duplicate names in GDPR sanitization process
- **Added comprehensive testing utilities module** with 20 tests covering Unit/Kernel/Functional scenarios (103 assertions total) …
> SLT-968: Resolve GDPR sanitization deployment failures with unique name generation
